
export const amenityIcons: Record<string, string> = {
  "coffee machine": "/Amenities/coffee-machine.svg",
  "heating": "/Amenities/heating .svg",
  "balcony": "/Amenities/balcony.svg",
  "iron & board": "/Amenities/ironing.svg",
  "sauna": "/Amenities/steam-room.svg",
  "television": "/Amenities/television.svg",
  "linens provided": "/Amenities/linens.svg",
  "air conditioning": "/Amenities/air-conditioner.svg",
  "not suitable for infants (under 2 years)": "/Amenities/pram.svg",
  "hair dryer": "/Amenities/hairdryer.svg",
  "lock up": "/Amenities/padlock.svg",
  "turn things off": "/Amenities/on-off-button.svg",
  "oven": "/Amenities/oven.svg",
  "microwave": "/Amenities/microwave-oven.svg",
  "smoke alarm": "/Amenities/fire-alarm.svg",
  "first aid kit": "/Amenities/first-aid-kit.svg",
  "free parking": "/Amenities/free-parking.svg",
  "trash bin": "/Amenities/trash.svg",
  "throw rubbish away": "/Amenities/trash.svg",
  "toaster": "/Amenities/toaster.svg",
  "pets allowed": "/Amenities/paw.svg",
  "guests": "/Amenities/people.svg",
  "no parties": "/Amenities/parties.svg",
  "dish washer": "/Amenities/dishwasher.svg",
  "emergency exit": "/Amenities/emergency-exit.svg",
  "garage": "/Amenities/garage.svg",
  "stove": "/Amenities/gas-stove.svg",
  "internet": "/Amenities/globe.svg",
  "no smoking": "/Amenities/no-smoking.svg",
  "no commercial photography": "/Amenities/no-photos.svg",
  "pantry": "/Amenities/pantry.svg",
  "garden": "/Amenities/park.svg",
  "no parties or events": "/Amenities/parties.svg",
  "refrigerator": "/Amenities/refrigerator.svg",
  "wifi": "/Amenities/wi-fi-icon.svg",
  "washing machine": "/Amenities/washing-machine.svg",
  "info": "/Amenities/light.svg"
};
