export type GalleryImage = {
  url: string;
  // alt: string;
  tag: "interior" | "exterior" | "surroundings";
  featured: boolean;
};

export const galleryImagesByLodge: Record<string, GalleryImage[]> = {
  "6514f268-d14a-42aa-89bb-2e6ac51b14c5": [
    // Glenridding Lodge
    {
      url: "/Glenridding/1.jpeg",
      // alt: "Glenridding exterior",
      tag: "exterior",
      featured: true,
    },
    {
      url: "/Glenridding/interior (2).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (3).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (4).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (5).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (6).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (7).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (8).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (9).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (10).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (11).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (12).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (13).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (14).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (15).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (16).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (17).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (18).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (19).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (20).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (21).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (22).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (23).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (24).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (25).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (26).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (27).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: true,
    },
    {
      url: "/Glenridding/interior (28).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (29).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (30).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (31).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Glenridding/interior (32).jpeg",
      // alt: "Glenridding interior",
      tag: "interior",
      featured: false,
    },
    // {
    //   url: "/Glenridding/pool.jpeg",
    //   // alt: "Glenridding interior",
    //   tag: "interior",
    //   featured: true,
    // },
    {
      url: "/Glenridding/exterior.jpeg",
      // alt: "Glenridding exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Glenridding/exterior (1).jpeg",
      // alt: "Glenridding exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Glenridding/exterior (2).jpeg",
      // alt: "Glenridding exterior",
      tag: "exterior",
      featured: true,
    },
    {
      url: "/Glenridding/exterior (3).jpeg",
      // alt: "Glenridding exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Glenridding/surroundings (1).jpeg",
      // alt: "Glenridding surroundings",
      tag: "surroundings",
      featured: true,
    },
    {
      url: "/Glenridding/surroundings (2).jpeg",
      // alt: "Glenridding surroundings",
      tag: "surroundings",
      featured: true,
    },
    {
      url: "/Glenridding/surroundings (3).jpeg",
      // alt: "Glenridding surroundings",
      tag: "surroundings",
      featured: false,
    },
  ],
  "465ec739-ab41-4e72-923c-bcf7925ea899": [
    // Water's Reach
    {
      url: "/Waters_Reach/1.jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: true,
    },
    {
      url: "/Waters_Reach/interior (1).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (2).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (3).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (4).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (5).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (6).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (7).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (8).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (9).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (10).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: true,
    },
    {
      url: "/Waters_Reach/interior (11).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (12).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (13).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (14).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (15).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (16).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/interior (17).jpg",
      // alt: "Water's Reach interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Waters_Reach/exterior.jpg",
      // alt: "Water's Reach exterior",
      tag: "exterior",
      featured: true,
    },
    {
      url: "/Waters_Reach/surroundings (1).jpg",
      // alt: "Water's Reach surroundings",
      tag: "surroundings",
      featured: false,
    },
    {
      url: "/Waters_Reach/surroundings (2).jpg",
      // alt: "Water's Reach surroundings",
      tag: "surroundings",
      featured: false,
    },
    {
      url: "/Waters_Reach/surroundings (3).jpg",
      // alt: "Water's Reach surroundings",
      tag: "surroundings",
      featured: false,
    },
    {
      url: "/Waters_Reach/surroundings (4).jpg",
      // alt: "Water's Reach surroundings",
      tag: "surroundings",
      featured: false,
    },
    {
      url: "/Waters_Reach/surroundings (5).jpg",
      // alt: "Water's Reach surroundings",
      tag: "surroundings",
      featured: false,
    },
  ],
  "5f2b3b3f-04e5-4a45-9c4e-2591711f23c9": [
    // Serenity
    {
      url: "/Serenity/1.png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: true,
    },
    {
      url: "/Serenity/interior (1).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (2).jpg",
      // alt: "Serenity interior",
      tag: "interior",
      featured: true,
    },
    {
      url: "/Serenity/interior (3).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (4).jpg",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (5).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (6).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (7).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (8).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (9).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (10).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (11).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (12).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (13).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (14).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (15).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (16).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (17).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (18).jpg",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (19).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/interior (20).png",
      // alt: "Serenity interior",
      tag: "interior",
      featured: false,
    },
    {
      url: "/Serenity/exterior (1).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: true,
    },
    {
      url: "/Serenity/exterior (2).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Serenity/exterior (3).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Serenity/exterior (4).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Serenity/exterior (5).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Serenity/exterior (6).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Serenity/exterior (7).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Serenity/exterior (8).png",
      // alt: "Serenity exterior",
      tag: "exterior",
      featured: false,
    },
    {
      url: "/Serenity/surroundings (1).png",
      // alt: "Serenity surroundings",
      tag: "surroundings",
      featured: true,
    },
    {
      url: "/Serenity/surroundings (2).png",
      // alt: "Serenity surroundings",
      tag: "surroundings",
      featured: true,
    },
  ],
};
